### ISSUE TITLE
Confirm on MSI H410I Pro Wifi

### ISSUE THREAD

**Issue by Semmelrocks** [gergap/nct6687d_mon#2]
Thanks to this small tool it shows much more than _lm-sensors_ with the Kernel driver _nct6683_.
You can see the board and chip as well here: [https://m.media-amazon.com/images/I/91MNlzN5O9L._AC_SL1500_.jpg](url)
Tested on Kernel 5.10.61 with a fanless system (so please don't wonder about the '0 rpm').

_sensors-detect_ shows:

Trying family `VIA/Winbond/Nuvoton/Fintek'...               Yes
Found unknown chip with ID 0xd592

Output of _nct6687d_mon_:
CPU         : 31.50 C
System      : 46.50 C
MOS         : 33.00 C
PCH         : 56.00 C
CPU Socket  : 32.00 C
PCIE_1      : 29.00 C
M2_1        : 23.50 C
VIN0 +12V   : 12.24 V
VIN1 +5V    : 5.07 V
VIN2 VCore  : 0.64 V
VIN3 SIO    : 1.00 V
VIN4 DRAM   : 1.21 V
VIN5 CPU IO : 0.95 V
VIN6 CPU SA : 1.05 V
VIN7 SIO    : 1.53 V
3VCC I/O +3.3: 3.32 V
SIO VTT     : 0.00 V
SIO VREF    : 0.00 V
SIO VSB     : 0.00 V
SIO AVSB    : 0.00 V
SIO VBAT    : 0.00 V
CPU Fan     : 0 rpm
PUMP Fan    : 0 rpm
SYS Fan 1   : 0 rpm
SYS Fan 2   : 0 rpm
SYS Fan 3   : 0 rpm
SYS Fan 4   : 0 rpm
SYS Fan 5   : 0 rpm
SYS Fan 6   : 0 rpm

You can compare here:[https://linux-hardware.org/?probe=e939c51829&log=sensors](url)
But it looks like he doesn't activate the Kernel module/driver _nct6683_ .

**Comment by gergap** [comment]
Good to know. Thanks for the feedback.
